### ISSUE TITLE
have 400 error

### ISSUE THREAD

**Issue by philippemarlin** [sogehige/sogeBot#1070]
### Additional informations

have this error can you help me ? 
2018-06-26T12:54:56.007 !!! ERROR !!! https://api.twitch.tv/kraken/channels/xxxxxxx/subscriptions?limit=100 - Request failed with status code 400 
xxxxxxx (channel id replace to hide)

Thanks lot

**Comment by Nugorra** [comment]
@sogehige why not just call when connecting and then use the tmi event? Someone who is neither affiliate or partner, otherwise gets  this error every 30 seconds.

**Comment by philippemarlin** [comment]
@sogehige no no im not affiliate or partner. Maybe its because my stream is offline ?

**Comment by sogehige** [comment]
tmi event is indeed used for subscribe or resub, although you cannot get subcount that way, thats why it is needed to fetch subscription api.

@Nugorra If user is not affiliate or partner, there should be error in console 'Broadcaster is not affiliate/partner, will not check subs' and then it should not do anything
https://github.com/sogehige/sogeBot/blob/master/libs/api.js#L247

400 is bad request error, which can be seen very rarely due to some random network issues for example.

@philippemarlin do you have set your settings.broadcaster_oauth? What format it is? Online/Offline status of stream doesn't change anything for this api call

I am considering of just hiding this error, but just want to be sure if there is not anything else what may be wrong.

**Comment by philippemarlin** [comment]
@sogehige yes i have like its write in your tutorial  format **oauth:xxxxxx**

**Comment by sogehige** [comment]
@philippemarlin already fixed for new version 👍

**Comment by philippemarlin** [comment]
You R Boss :)
